require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'brandspring' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'RNImageMarker', :path => '../node_modules/react-native-image-marker'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  target 'brandspringTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5', 'Flipper-RSocket' => '1.3' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end